service: sns-sqs-lambda-sls-ts
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 256
  timeout: 10

functions: ${file(./resources/functions.yml)}

resources:
  - ${file(./resources/sqs.yml)}
  - ${file(./resources/sns.yml)}