Resources:
  TestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: test-topic
  TestSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref TestTopic
      Endpoint: !GetAtt TestQueue.Arn