Resources:
  TestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test-queue
      SqsManagedSseEnabled: false
  TestQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow TestTopic to publish to TestQueue"
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt TestQueue.Arn
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref TestTopic
      Queues:
        - Ref: TestQueue